### ISSUE TITLE
If it turns out that a response will be an error (4xx, 5xx) we want to be able to remove headers set by plugins.

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [google/go-safeweb#102]
Imagine that we have two plugins installed. The first one claims and sets a header in the `Before` phase. The other plugins `Before` phase runs and an error occurs, so the plugin writes an error response (4xx, 5xx). Now, what happens to the header that the first plugin set? Depending on the plugin this header should probably not be present on error responses. So how do we remove it?

One option would be that all error responses, 4xx and 5xx, automatically remove all headers and set their own ones. But this becomes a problem since we might want CSP on error responses. CSP is handled by a plugin.

Another solution is that all plugins are responsible for removing their headers in the commit phase if it sees that the response is an error.

This needs to be discussed further.

**Comment by kele** [comment]
See also #189.

**Comment by kele** [comment]
It seems that some headers should be added even to error responses, and some could be stripped. I don't think the framework needs to support this feature natively and this can be instead handled by a custom `Interceptor`.

As a side note: the API has changed in a way where `Interceptor.Commit` cannot trigger `ResponseWriter.WriteError` anymore.

@empijei WDYT?

**Comment by empijei** [comment]
I think we should start drawing some flowcharts of the various phases and clearly document what can and cannot be done based on what happens.

That said, how would you remove some specific headers from errors with the current API?

**Comment by kele** [comment]
Two scenarios:

1. The `InterceptorFoo` itself can realize that a header should not be set in the `Commit` phase. - This is self-explanatory and easy to achieve.
2. `InterceptorFoo` has already run, claimed and set the `Bar` header inside its `Commit` phase. Now, another interceptor runs (continued `Commit` phase) and it turns out that the `Bar` header should be cleaned up. - This seems like a complicated case and I'l like to see a real world scenario. But even assuming that there exists one, I still believe `InterceptorFoo` should be in full control of the `Bar` header, so instead of creating a framework way of overriding the claim, I'd suggest that the package that provides `InterceptorFoo` also provides API to clear it up.

Nevertheless, It'd be nice to see some real world examples where the above solutions don't work/are too clunky.

**Comment by empijei** [comment]
If the InterceptorFoo provided a way to clean stuff up, when and where would that be run? Are you proposing to add a Cleanup phase or should it just run that stuff on error? If so... don't we prevent response editing in the error phase?

**Comment by kele** [comment]
We don't have an `Error` phase anymore. There's just `Before` and `Commit`. `Commit` can alter the response (but not alter framework's execution).

**Comment by empijei** [comment]
Will commit always run, even if an error was written before? Do we expect commit calls to check if they're committing an error?

**Comment by kele** [comment]
> Will commit always run, even if an error was written before?

I don't understand this question. Before what?

> Do we expect commit calls to check if they're committing an error?

The ones that care about it, yes.

A `panic` (500) currently clears all the headers: https://github.com/google/go-safeweb/blob/d4d7197bce5996f2440b9fa9559990b1c8ae8bdf/safehttp/flight.go#L78.

I think this is the correct behavior as we no longer can pass control back to the interceptors. If an interceptor or the `Dispatcher` wants to clean up some headers during normal flow, this can be implemented quite easily.

**Comment by kele** [comment]
ping @empijei

**Comment by empijei** [comment]
To wrap up: interceptors that care about this behavior should check the status code in Commit, and potentially remove headers.

I don't think any of our current interceptors need to do that.
