### ISSUE TITLE
Add a Server type

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#107]
One important security feature is providing safe defaults for the Server type. For example there is [a quite outdated post](https://blog.cloudflare.com/exposing-go-on-the-internet/) that explains some things that should be added to a `Server` type before exposing it to the internet.

We should provide a wrapper type that constructs servers with safe defaults.

@filosottile can probably help identify the stuff that needs updating from that original post.

**Comment by maramihali** [comment]
Another article that provides useful information on timeouts is this [one](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/)

Thing to keep in mind:
* we need to set either `ReadTimeout` (header + body) or `ReadHeaderTimeout` to prevent server resource exhaustation and DoS attacks
* the Server's `Handler` field should never be nil, but set to an instantiated `ServeMux` as otherwise handlers will be registered on the `http.DefaultServeMux` which is a global that all imported packages (and imports of imports) have access to and this can lead to information leakages
* we need to disallow the usage of `http.ListenAndServe` or `http.Serve` and could create equivalents with sane defaults

**Comment by kele** [comment]
After discussing this with @empijei: we should aim at providing a default safe `Server` type for now without much configuration options for v0.1.
