### ISSUE TITLE
Add support to set 2XX statuses that are not 200 and 204

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#151]
There currently is no way to set any of the 2XX statuses, so Partial Content is not doable.

**Comment by kele** [comment]
@maramihali: Could you elaborate on how you want to achieve it? The linked PR uses one approach (i.e. introduces `SetStatusCode` method on a `ResponseWriter`). I'm curious what are the alternatives and which one we'd like to pursue.

Also, what are the requirements? One I know, is: don't make an error-prone API that allows setting the status code after the response has been written. **What are the others?**

Some approaches I see here:
- `rw.Write(response, code)` -- mandatory always
- `rw.WriteOK(response)` and `rw.Write(response, code)`
- `rw.Write(response)` and `rw.WriteCode(reponse, code)`
` `rw.StatusCode(code)` and then `rw.Write(response)` -- i.e. what the linked PR does now

**Comment by maramihali** [comment]
**Goals**: Users of the framework might want to set a 1xx (I think) or 2xx status code for particular responses. Currently, our framework either sets the response status to `204 No Content` for a response without content or to `200` for a successful response. We need to integrate a way of achieving this in our API to motivate the use of the `safehttp` package since a common error in using the `net/http` package is calling `rw.WriteHeader(statusCode)` after having written the body. There are some alternatives we can consider here (as @kele mentions above):
1.  have an exported field `Code` that the developer can set and we only care about it if it's set to 1xx or 2xx and otherwise report an error; if it's set to 0 we return a `safehttp.StatusOK`
**Pros**:
* most simple? (after implementing it I think it's not the right way to go though)
**Cons**:
* error-prone since the user might set it after the response has been written
2. have an additional `rw.SetStatusCode(code)` method (what the PR does) besides the write methods
**Pros**:
* we keep the writing part from our API like the one in `net/http` while introducing the functionality
**Cons**:
* we need to be careful with how we handle errors and what we deem as a "valid" call of `rw.SetStatusCode`
* are we allowing headers to be set afterwards?
3.  make the status code mandatory in the write method i.e. `rw.Write(response,code)`
**Pros**:
* hard to omit setting the status code properly
* we don't need to deal with the issue of whether we want to allow setting other headers after setting the status code since after calling write it's clear that this is not possible anymore (also in 4)
**Cons**:
* we distance ourselves from the standard API and one of our goals is keeping `safehttp` as close as possible to the standard API, especially for main features like the `ResponseWriter`
4. have both `rw.WriteCode(response, statusCode)` and `rw.Write(response)` in the API
**Pros**:
* most commonly we just want to return `safehttp.StatusOK` I guess and having the `rw.Write(response)` methods avoids repeatedly having to pass it to the `rw.WriteCode` method
**Cons**:
* if we keep having separate writing functions for different responses this would mean we have 6 (or even more) writing method
* we slightly distance ourselves from the standard API and people familiar with the `net/http` package might just ignore the `rw.WriteCode` method

**Comment by maramihali** [comment]
@kele, @empijei any thoughts on this ?
