### ISSUE TITLE
flight.WriteError calling http.ResponseWriter.WriteHeader causes DefaultDispatcher to superfluously call WriteHeader the second time

### ISSUE THREAD

**Issue by kele** [google/go-safeweb#239]
A log is printed by the `net/http` package about calling `WriteHeader` twice:

```
2021/01/29 10:59:36 http: superfluous response.WriteHeader call from github.com/google/go-safeweb/safehttp.DefaultDispatcher.Error (default_dispatcher.go:92)
```

This is becase `flight.WriteError` calls `WriteHeader`, and then the `DefaultDispatcher` calls `http.Error` which also calls `WriteHeader`.

**Should `flight.WriteError` call `WriteHeader`, or should this be the responsibility of the `Dispatcher`?**

**Comment by mikue1** [comment]
Looking at `dispatcher.go`, the current interface says:

```
	// Error writes an ErrorResponse to the underlying http.ResponseWriter.
	//
	// It should return an error if the writing operation fails or if the
	// provided Response should not be written to the http.ResponseWriter
	// because it's unsafe.
	Error(rw http.ResponseWriter, resp ErrorResponse) error
```

If we are going to keep it that way, it seems natural that `flight` should *only* (attempt to) write headers itself, if the dispatcher returns an error. If dispatcher succeeds, I don't see how `writes an ErrorResponse to the underlying http.ResponseWriter.` would not lead to headers being written already.

Proposed patch would be to move `flight.go`, line 151 `f.rw.WriteHeader(int(resp.Code()))` inside the error handling (or just remove that line, because the error handling panics and terminates the connection...)

@kele wdyt?

**Comment by kele** [comment]
This makes it inconsistent with `flight.Write`, which sets the code before the `Dispatcher` is invoked (also, `Dispatcher.Write` is not expected to write the code). I'd argue that the `Dispatcher` should *not* write the response code.

Currently it does only because I've used `http.Error` instead of a `net/http.ResponseWriter.Write` and I consider this an oversight.
