### ISSUE TITLE
Allow using ServeMux as a factory for net/http.Handlers

### ISSUE THREAD

**Issue by kele** [google/go-safeweb#245]
Currently to use the `safehttp` package handlers together with a `net/http.ServeMux` (e.g. during migration) one needs to pass the whole `ServeMux` as a `net/http.Handler` (possible because `safehttp.ServeMux` satisfies the interface).

Instead, it'd make sense to add a `func (m *ServeMux) Handler(path string) http.Handler` method, mostly for clarity of intent and easy discoverability.

Note: additional benefit of doing this is avoiding double-routing that otherwise happens when `ServeMux` is used as a handler for `net/http.ServeMux`.

**Comment by empijei** [comment]
safehttp wraps handlers in a safe way, and allows you to do that on a ServeMux that implements http.Handler.

During migrations it might be useful to build just a http.Handler using a ServeMux (so that all middleware will run on it) and register that on a standard http.ServeMux.

The idea is to provide something to allow users to gradually convert handler after handler to be safe handlers (and have them coexist with standard ones) until we can finally just switch to a safe ServeMux.

To do so we thought about using ServeMux as a factory that, given a safe handler, can return a standard one.

Does it make more sense now?
