### ISSUE TITLE
Why is Handle signature taking (path, method, handler) instead of (method, path, handler)?

### ISSUE THREAD

**Issue by empijei** [google/go-safeweb#315]
Just... why?

Seems to me like method should go before path.

**Comment by kele** [comment]
In the RPC world, we'd have `mux.Handle(methodName, handler)`.

In abstract, it seems to me that path is more important than method. It seems like a judgement call, but the rule of thumb I usually follow is: how much information do I get by reading just the first few arguments? In this case, `mux.Handle(POST, ...)` gives me no information about the logic, but about a technical aspect of the service. `mux.Handle("/note", ...)` informs me that there is an endpoint for notes.

One could argue that the `GET/POST` distinction is vital, because it signals whether an endpoint handlers reads or writes, but I still see it as a lower level of abstraction than the path itself.
